-- ****************************** SqlDBM: MySQL *****************************
-- * Generated by SqlDBM: Hotel Booking, v1 by kushagra.jain@zemosolabs.com *



-- ************************************** `Hotel`

CREATE TABLE `Hotel`
(
 `Hotel_id`      int NOT NULL ,
 `Hotel_name`    varchar(45) NOT NULL ,
 `Hotel_address` varchar(45) NOT NULL ,

PRIMARY KEY (`Hotel_id`)
);


-- ****************************** SqlDBM: MySQL *****************************
-- * Generated by SqlDBM: Hotel Booking, v1 by kushagra.jain@zemosolabs.com *



-- ************************************** `Customer_FirstTime`

CREATE TABLE `Customer_FirstTime`
(
 `Customer_Addhar_id` isnumeric NOT NULL ,
 `Customer_name`      varchar(45) NOT NULL ,
 `Hotel_id`           int NOT NULL ,
 `customer_gender`    varchar(45) NOT NULL ,
 `customer_age`       tinyint NOT NULL ,
 `Customer_phone_no`  bigint NOT NULL ,

PRIMARY KEY (`Customer_Addhar_id`),
KEY `FK_23` (`Hotel_id`),
CONSTRAINT `FK_21` FOREIGN KEY `FK_23` (`Hotel_id`) REFERENCES `Hotel` (`Hotel_id`)
);



-- ****************************** SqlDBM: MySQL *****************************
-- * Generated by SqlDBM: Hotel Booking, v1 by kushagra.jain@zemosolabs.com *



-- ************************************** `Loyal_Customer`

CREATE TABLE `Loyal_Customer`
(
 `LCustomer_Addhar_id` isnumeric NOT NULL ,
 `Customer_name`       varchar(45) NOT NULL ,
 `Hotel_id`            int NOT NULL ,
 `LCustomer_gender`    varchar(45) NOT NULL ,
 `LCustomer_age`       tinyint NOT NULL ,
 `LCustomer_phone_no`  bigint NOT NULL ,

PRIMARY KEY (`LCustomer_Addhar_id`),
KEY `FK_26` (`Hotel_id`),
CONSTRAINT `FK_24` FOREIGN KEY `FK_26` (`Hotel_id`) REFERENCES `Hotel` (`Hotel_id`)
);

